/**
 * Cost & Scalability Model (Source of Truth Aggregator)
 *
 * Canonical cost constants live in: src/config/tierCosts.ts
 * This module aggregates those constants + provides scenario math for UI/docs.
 */

import {
  DREAM_ANALYSIS_COSTS,
  VIDEO_COSTS,
  TRANSCRIPTION_COSTS,
  TTS_COSTS,
  REFLECT_AI_COSTS,
  SYMBOLICA_AI_COSTS,
  COMMUNITY_COSTS,
  MONTHLY_COST_ESTIMATES,
  calculateTranscriptionCost,
  calculateTTSCost,
  calculateReflectAICost,
  calculateSymbolicaAICost,
  calculateVideoCost,
} from '@/config/tierCosts'

export type VideoType = 'dreamcatcher' | 'dreamworlds' | 'dreamworlds-vip'

export type CostLineItem = {
  key: string
  label: string
  unit: string
  unitCostUsd: number
  notes?: string
}

export type ScenarioInputs = {
  /** Total dreams analyzed (text + image pipeline). */
  dreams: number
  /** Optional voice recordings transcribed (minutes). */
  transcriptionMinutes: number
  /** ReflectAI messages (premium tiers). */
  reflectAiMessages: number
  /** Symbolica analyses (premium tiers). */
  symbolicaAnalyses: number
  /** TTS characters generated. */
  ttsCharacters: number
  /** Number of videos generated by type. */
  videos: Record<VideoType, number>
  /** Community actions (share/like/view tracking). */
  communityShares: number
  communityLikes: number
  communityViews: number
}

export const DEFAULT_SCENARIO: ScenarioInputs = {
  dreams: 10,
  transcriptionMinutes: 15,
  reflectAiMessages: 50,
  symbolicaAnalyses: 50,
  ttsCharacters: 2800 * 10,
  videos: {
    dreamcatcher: 5,
    dreamworlds: 1,
    'dreamworlds-vip': 0,
  },
  communityShares: 25,
  communityLikes: 150,
  communityViews: 2000,
}

export function getUnitCostLineItems(): CostLineItem[] {
  return [
    {
      key: 'dream_analysis_total',
      label: 'Dream analysis (title+tags+interpretation+1 HD image)',
      unit: 'per dream',
      unitCostUsd: DREAM_ANALYSIS_COSTS.TOTAL_PER_DREAM,
      notes: 'Uses gpt-4.1-mini for interpretation + 1× HD image',
    },
    {
      key: 'video_dreamcatcher',
      label: 'Video generation (Dreamcatcher 6s)',
      unit: 'per video',
      unitCostUsd: calculateVideoCost('dreamcatcher'),
    },
    {
      key: 'video_dreamworlds',
      label: 'Video generation (Dreamworlds 45s)',
      unit: 'per video',
      unitCostUsd: calculateVideoCost('dreamworlds'),
    },
    {
      key: 'video_dreamworlds_vip',
      label: 'Video generation (Dreamworlds VIP)',
      unit: 'per video',
      unitCostUsd: calculateVideoCost('dreamworlds-vip'),
    },
    {
      key: 'transcription',
      label: 'Voice transcription',
      unit: 'per minute',
      unitCostUsd: TRANSCRIPTION_COSTS.PER_MINUTE,
      notes: `Min charge: $${TRANSCRIPTION_COSTS.MIN_CHARGE.toFixed(4)}`,
    },
    {
      key: 'reflect_ai_message_avg',
      label: 'ReflectAI message (avg)',
      unit: 'per message',
      unitCostUsd: REFLECT_AI_COSTS.COST_PER_MESSAGE,
      notes: `${REFLECT_AI_COSTS.AVG_INPUT_TOKENS} in / ${REFLECT_AI_COSTS.AVG_OUTPUT_TOKENS} out tokens avg`,
    },
    {
      key: 'symbolica_analysis_avg',
      label: 'Symbolica analysis (avg)',
      unit: 'per analysis',
      unitCostUsd: SYMBOLICA_AI_COSTS.COST_PER_ANALYSIS,
      notes: `${SYMBOLICA_AI_COSTS.AVG_INPUT_TOKENS} in / ${SYMBOLICA_AI_COSTS.AVG_OUTPUT_TOKENS} out tokens avg`,
    },
    {
      key: 'tts_character',
      label: 'Text-to-speech',
      unit: 'per character',
      unitCostUsd: TTS_COSTS.PER_CHARACTER,
      notes: 'Assumes $15 / 1M characters',
    },
    {
      key: 'community_share',
      label: 'Community share',
      unit: 'per share',
      unitCostUsd: COMMUNITY_COSTS.SHARE_COST,
    },
    {
      key: 'community_like',
      label: 'Community like',
      unit: 'per like',
      unitCostUsd: COMMUNITY_COSTS.LIKE_COST,
    },
    {
      key: 'community_view',
      label: 'Community view tracking',
      unit: 'per view',
      unitCostUsd: COMMUNITY_COSTS.VIEW_TRACKING,
    },
  ]
}

export function calculateScenarioCostUsd(inputs: ScenarioInputs) {
  const dreamCost = inputs.dreams * DREAM_ANALYSIS_COSTS.TOTAL_PER_DREAM
  const transcriptionCost = calculateTranscriptionCost(inputs.transcriptionMinutes)
  const reflectAiCost =
    inputs.reflectAiMessages *
    calculateReflectAICost(REFLECT_AI_COSTS.AVG_INPUT_TOKENS, REFLECT_AI_COSTS.AVG_OUTPUT_TOKENS)
  const symbolicaCost =
    inputs.symbolicaAnalyses *
    calculateSymbolicaAICost(SYMBOLICA_AI_COSTS.AVG_INPUT_TOKENS, SYMBOLICA_AI_COSTS.AVG_OUTPUT_TOKENS)
  const ttsCost = calculateTTSCost(inputs.ttsCharacters)

  const videoCost =
    (inputs.videos.dreamcatcher || 0) * VIDEO_COSTS.DREAMCATCHER_6S +
    (inputs.videos.dreamworlds || 0) * VIDEO_COSTS.DREAMWORLDS_45S +
    (inputs.videos['dreamworlds-vip'] || 0) * VIDEO_COSTS.DREAMWORLDS_VIP

  const communityCost =
    inputs.communityShares * COMMUNITY_COSTS.SHARE_COST +
    inputs.communityLikes * COMMUNITY_COSTS.LIKE_COST +
    inputs.communityViews * COMMUNITY_COSTS.VIEW_TRACKING

  const total = dreamCost + transcriptionCost + reflectAiCost + symbolicaCost + ttsCost + videoCost + communityCost

  return {
    dreamCost,
    transcriptionCost,
    reflectAiCost,
    symbolicaCost,
    ttsCost,
    videoCost,
    communityCost,
    total,
  }
}

export function getMonthlyTierCostEstimates() {
  return MONTHLY_COST_ESTIMATES
}

export function formatUsd(value: number) {
  const safe = Number.isFinite(value) ? value : 0
  if (safe === 0) return '$0.00'
  if (safe < 0.01) return `$${safe.toFixed(4)}`
  return `$${safe.toFixed(2)}`
}
